---
- name: Debug limit field
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Debug Host to Automate and Inventory to Sync
      ansible.builtin.debug:
        msg: "{{ host_to_automate }} and inventory source to sync {{  inventory_source_to_sync }}"
